services:
    node:
        build:
            context: .
        env_file: [".env"]
        volumes:
            - .:/app
            - ./docker/node/docker-entrypoint.dev.sh:/usr/local/bin/docker-entrypoint.dev.sh
        depends_on:
            - postgres
            - redis
        entrypoint: ['/usr/local/bin/docker-entrypoint.dev.sh']
        command: ['tail', '-f', '/dev/null']

    postgres:
        image: postgres:16.0-alpine3.18
        environment:
            POSTGRES_PASSWORD: postgres
        ports:
            - ${HOST_POSTGRES_PORT}:5432
        volumes:
            - postgres:/var/lib/postgresql/data

    redis:
        image: redis:7.2.1-alpine3.18

volumes:
    postgres: ~
