services:
    node:
        build:
            context: .
            target: dev
        env_file: [".env"]
        volumes:
            - .:/app
            - ./docker/node/docker-entrypoint.base.sh:/usr/local/bin/docker-entrypoint.base.sh
            - ./docker/node/docker-entrypoint.dev.sh:/usr/local/bin/docker-entrypoint.dev.sh
        ports:
            - "${HOST_HTTP_PORT}:${HTTP_PORT}"
        depends_on:
            - postgres
        command: ["tail", "-f", "/dev/null"]

    postgres:
        image: postgres:16.0-alpine3.18
        environment:
            POSTGRES_PASSWORD: postgres
        ports:
            - ${HOST_POSTGRES_PORT}:5432
        volumes:
            - postgres:/var/lib/postgresql/data

volumes:
    postgres: ~
